### ISSUE TITLE
Add support for Beta Cluster

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/performance-WikimediaDebug#12]
Would be nice to also support Beta Cluster. For it, there wouldn't be a need for a dropdown menu given it doesn't (yet) have a debug proxy backend for specific hosts, but it does have the Varnish code to bypass the cache, so a simple value like "X-Wikimedia-Debug: 1" should work.

@bd808 Thoughts?

**Comment by bd808** [comment]
I think this would only require adding the beta cluster domains to urlPatterns in background.js. The backend host would still be passed, but that would just be ignored as nothing would be there to read and handle that part of the `X-Wikimedia-Debug` header.

We'd probably want to add something that also noticed that the access was to the beta cluster and switch the logstash url to point to the beta deploy too.

**Comment by Krinkle** [comment]
Re-closing and filing new issues #14 and #15.

**Comment by lucaswerkmeister** [comment]
Even with #14 and #15 still open, could you perhaps still release a version with cadfc9f? When working on tools, it would be very useful to just check if the header is present on the backend, regardless of which value the extension sends. Or do you want to avoid this due to compatibility concerns?
