### ISSUE TITLE
Add support for 'forceprofile' attribute

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/performance-WikimediaDebug#17]
Commit <https://gerrit.wikimedia.org/r/415201> adds support for `forceprofile` to be triggered by header attribute (in addition to the current support for query parameter).

This issue is a reminder to consider adding a checkbox to the WikimediaDebug extension for enabling this attribute. We'll need to come up with an intuitive label, to avoid confusion.

We have:
* Profile: Captures a complete CPU/Memory call graph profile, sends to XHGui, has a footer link.
* Log: Overrides the normal SPI config to enable logging of all channels and severity, sends to Logstash, has a footer link.
* Read-only: Enables database-ReadOnly mode in MediaWiki.

And we'll add:
* (Label TBD): Capture a basic call graph profile with wall-time spent, and append to web response as code comment. (Typically HTML comment or JS/CSS comment).

**Comment by bd808** [comment]
> (Label TBD)

How about "call graph" or "inline profile"?

**Comment by Krinkle** [comment]
Thanks. Went with "Inline profile".

|Last release
|--
|<img width="313" alt="Screenshot 2019-11-27 at 04 35 13" src="https://user-images.githubusercontent.com/156867/69694479-d02be100-10d0-11ea-809a-ee877375a655.png">

|Current master
|--
|<img width="306" alt="Screenshot 2019-11-27 at 04 35 08" src="https://user-images.githubusercontent.com/156867/69694478-d02be100-10d0-11ea-9aee-ae07e60c699d.png">
