### ISSUE TITLE
Update Homepage/Support link in Firefox Add-ons page

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/performance-WikimediaDebug#9]
<https://addons.mozilla.org/en-US/firefox/addon/wikimedia-debug-header/> still points to the old repo.

**Comment by bd808** [comment]
I changed the "homepage" link to https://wikitech.wikimedia.org/wiki/X-Wikimedia-Debug and the "support" link to https://github.com/wikimedia/WikimediaDebug/issues.
